"""
CUIN v2 Control Plane - Candidates API Routes

Endpoints for viewing candidate pairs generated by blocking.
"""

from typing import Optional

from fastapi import APIRouter, HTTPException

from services.run_service import get_run_service

router = APIRouter()


# ============================================
# Routes
# ============================================

@router.get("/run/{run_id}")
async def list_candidates(
    run_id: str,
    page: int = 1,
    page_size: int = 50,
    min_score: Optional[float] = None,
    blocking_method: Optional[str] = None
) -> dict:
    """
    List candidate pairs for a run.
    """
    run_service = get_run_service()
    orchestrator = run_service.get_orchestrator(run_id)
    
    if not orchestrator:
        run = run_service.get_run(run_id)
        if not run:
            raise HTTPException(status_code=404, detail="Run not found")
        return {
            "candidates": [],
            "total": 0,
            "page": page,
            "page_size": page_size,
            "message": "Run not yet executed or candidates not available"
        }
    
    candidates = orchestrator._candidates
    
    # Filter by blocking method if specified
    if blocking_method:
        candidates = [
            c for c in candidates
            if blocking_method in c.blocking_reasons
        ]
    
    # Paginate
    total = len(candidates)
    start = (page - 1) * page_size
    end = start + page_size
    paged = candidates[start:end]
    
    return {
        "candidates": [
            {
                "a_key": c.a_key,
                "b_key": c.b_key,
                "blocking_reasons": c.blocking_reasons,
                "block_key_sample": c.block_key_sample,
            }
            for c in paged
        ],
        "total": total,
        "page": page,
        "page_size": page_size
    }


@router.get("/run/{run_id}/stats")
async def get_candidate_stats(run_id: str) -> dict:
    """
    Get statistics about candidate pairs for a run.
    """
    run_service = get_run_service()
    orchestrator = run_service.get_orchestrator(run_id)
    
    if not orchestrator:
        run = run_service.get_run(run_id)
        if not run:
            raise HTTPException(status_code=404, detail="Run not found")
        return {
            "total_candidates": 0,
            "blocking_method_breakdown": {},
            "message": "Run not yet executed or candidates not available"
        }
    
    candidates = orchestrator._candidates
    
    # Count by blocking method
    method_counts = {}
    for c in candidates:
        for method in c.blocking_reasons:
            method_counts[method] = method_counts.get(method, 0) + 1
    
    return {
        "total_candidates": len(candidates),
        "blocking_method_breakdown": method_counts,
        "unique_records": len(set(
            key for c in candidates for key in [c.a_key, c.b_key]
        )),
    }


@router.get("/{pair_id}")
async def get_candidate(pair_id: str) -> dict:
    """
    Get details of a specific candidate pair.
    
    pair_id format: a_key:b_key or just search across all runs.
    """
    run_service = get_run_service()
    
    # Try to parse pair_id as a_key:b_key
    if ":" in pair_id:
        a_key, b_key = pair_id.split(":", 1)
    else:
        raise HTTPException(
            status_code=400,
            detail="Invalid pair_id format. Expected 'a_key:b_key'"
        )
    
    # Search across all runs
    runs, _ = run_service.list_runs(page=1, page_size=100)
    
    for run in runs:
        orchestrator = run_service.get_orchestrator(run.run_id)
        if orchestrator:
            for candidate in orchestrator._candidates:
                if candidate.a_key == a_key and candidate.b_key == b_key:
                    # Get the records
                    record_a = orchestrator._records.get(a_key)
                    record_b = orchestrator._records.get(b_key)
                    
                    return {
                        "pair_id": pair_id,
                        "run_id": run.run_id,
                        "a_key": a_key,
                        "b_key": b_key,
                        "blocking_reasons": candidate.blocking_reasons,
                        "block_key_sample": candidate.block_key_sample,
                        "record_a": record_a,
                        "record_b": record_b,
                    }
    
    raise HTTPException(status_code=404, detail="Candidate pair not found")
