"""
Export Splink Clusters to Neo4j

This module exports entity resolution clusters generated by Splink
into a Neo4j graph database.

The export creates:
- EntityCluster nodes for each cluster
- Entity nodes for records in clusters
- MEMBER_OF relationships from entities to clusters
- DUPLICATE_OF relationships between matching entities

Usage:
    python -m er.splink_commands all --output my_clustering_results.csv
    python -m er.splink_neo4j_export --clusters-csv my_clustering_results.csv
    
    Or programmatically:
    from engine.spark_er.splink_neo4j_export import export_clusters_csv_to_neo4j
    export_clusters_csv_to_neo4j(spark, clusters_csv, records_df)
"""

# =============================================================================
# IMPORTANT: Set HADOOP_HOME before ANY other imports (required for Windows)
# This MUST be done before PySpark/Java initializes
# =============================================================================
import os
import sys
import platform

if platform.system() == "Windows":
    # Check standard installation location
    _hadoop_home = r"C:\hadoop"
    _winutils_path = os.path.join(_hadoop_home, "bin", "winutils.exe")
    
    if os.path.exists(_winutils_path):
        os.environ["HADOOP_HOME"] = _hadoop_home
        os.environ["hadoop.home.dir"] = _hadoop_home
        # Also add to PATH if not already there
        _hadoop_bin = os.path.join(_hadoop_home, "bin")
        if _hadoop_bin not in os.environ.get("PATH", ""):
            os.environ["PATH"] = _hadoop_bin + os.pathsep + os.environ.get("PATH", "")
    else:
        # Check if HADOOP_HOME is already set in environment
        _env_hadoop = os.environ.get("HADOOP_HOME", "")
        if not _env_hadoop or not os.path.exists(os.path.join(_env_hadoop, "bin", "winutils.exe")):
            print("=" * 70)
            print("WARNING: Hadoop winutils.exe not found!")
            print("=" * 70)
            print(f"Expected location: {_winutils_path}")
            print("\nTo fix this, run:")
            print("  python setup_hadoop_windows.py")
            print("\nOr download manually from:")
            print("  https://github.com/cdarlint/winutils")
            print("=" * 70)
# =============================================================================

import glob
import multiprocessing
from typing import List, Dict, Any, Iterator, Optional
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Check Neo4j driver availability
try:
    from neo4j import GraphDatabase
except ImportError:
    print("=" * 70)
    print("ERROR: Neo4j driver not installed")
    print("=" * 70)
    print("\nNeo4j driver is required for exporting to Neo4j.")
    print("\nTo install:")
    print("  pip install neo4j")
    print("\nOr install all requirements:")
    print("  pip install -r requirements.txt")
    print("=" * 70)
    sys.exit(1)

# Check PySpark availability
try:
    from pyspark.sql import SparkSession, DataFrame
    from pyspark.sql import functions as F
    try:
        from py4j.protocol import Py4JJavaError
    except ImportError:  # pragma: no cover - fallback for non-standard installs
        Py4JJavaError = Exception
except ImportError:
    print("=" * 70)
    print("ERROR: PySpark not installed")
    print("=" * 70)
    print("\nPySpark is required for loading data.")
    print("\nTo install:")
    print("  pip install pyspark")
    print("=" * 70)
    sys.exit(1)

# Configuration from environment variables
NEO4J_URI = os.getenv("NEO4J_URI", "bolt://localhost:7687")
NEO4J_USER = os.getenv("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD", "password")
CACHE_DIR = os.getenv("CACHE_DIR", "data_source")
CACHE_FORMAT = os.getenv("CACHE_FORMAT", "parquet")
CUSTOMER_AGGREGATED_PATH = os.getenv("CUSTOMER_AGGREGATED_PATH", "customer_aggregated")
CLUSTER_ID_FIELD = "cluster_id"
ENTITY_ID_FIELD = "entity_id"
_NEO4J_DEFAULT_BATCH_SIZE = 5000
# Target number of MEMBER_OF relationships per transaction.
_MEMBER_BATCH_TARGET = 100000
# Default materialization folder is relative to the current working directory.
NEO4J_MATERIALIZE_DIR = os.getenv("NEO4J_MATERIALIZE_DIR", "neo4j_materialized")
# Default entity properties to export to Neo4j. Override with NEO4J_ENTITY_COLUMNS
# (comma-separated list) to control which record columns are written.
# Defaulting to an empty list avoids heavy joins and speeds up exports.
# Note: This changes the default export to entity_id-only; set NEO4J_ENTITY_COLUMNS
# to include additional record properties if needed.
DEFAULT_ENTITY_EXPORT_COLUMNS: List[str] = []
raw_entity_columns = os.getenv("NEO4J_ENTITY_COLUMNS")
if raw_entity_columns is None or not raw_entity_columns.strip():
    ENTITY_EXPORT_COLUMNS = DEFAULT_ENTITY_EXPORT_COLUMNS
else:
    parsed_entity_columns = [
        column.strip()
        for column in raw_entity_columns.split(",")
        if column.strip()
    ]
    if parsed_entity_columns:
        ENTITY_EXPORT_COLUMNS = parsed_entity_columns
    else:
        print(
            "Warning: NEO4J_ENTITY_COLUMNS is set but contains no valid columns. "
            "Using default entity export columns."
        )
        ENTITY_EXPORT_COLUMNS = DEFAULT_ENTITY_EXPORT_COLUMNS


def _exportable_entity_columns(columns: List[str]) -> List[str]:
    """Filter exportable entity columns present in the dataset, excluding ID fields."""
    column_set = set(columns)
    return [
        col
        for col in ENTITY_EXPORT_COLUMNS
        if col in column_set and col not in {"entity_id", "cluster_id"}
    ]


def _format_count(value: Optional[int]) -> str:
    return f"{value:,}" if value is not None else "unknown"


def _parse_bool_env(var_name: str, default: bool = False) -> bool:
    value = os.getenv(var_name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes"}


def _normalize_neo4j_batch_size(value: int, source: str) -> int:
    if value <= 0:
        print(
            f"Warning: {source} {value} is invalid; using default {_NEO4J_DEFAULT_BATCH_SIZE}"
        )
        return _NEO4J_DEFAULT_BATCH_SIZE
    return value


def _resolve_neo4j_batch_size(cli_value: Optional[int]) -> int:
    if cli_value is not None:
        return _normalize_neo4j_batch_size(cli_value, "neo4j batch size")
    batch_env = os.getenv("NEO4J_BATCH_SIZE")
    if batch_env:
        try:
            return _normalize_neo4j_batch_size(int(batch_env), "NEO4J_BATCH_SIZE")
        except ValueError:
            print(
                f"Warning: NEO4J_BATCH_SIZE='{batch_env}' is invalid; "
                f"using default {_NEO4J_DEFAULT_BATCH_SIZE}"
            )
            return _NEO4J_DEFAULT_BATCH_SIZE
    return _NEO4J_DEFAULT_BATCH_SIZE


def get_cache_file_path() -> str:
    """Get the path to the cached data file."""
    if CACHE_FORMAT == "parquet":
        return os.path.join(CACHE_DIR, "oracle_data.parquet")
    if CACHE_FORMAT == "json":
        return os.path.join(CACHE_DIR, "oracle_data.json")
    if CACHE_FORMAT == "csv":
        return os.path.join(CACHE_DIR, "oracle_data.csv")
    raise ValueError(f"Unsupported cache format: {CACHE_FORMAT}")


def create_spark_session() -> SparkSession:
    """Create Spark session configured for parallel processing."""
    cpu_cores = multiprocessing.cpu_count()
    print("=" * 70)
    print("INITIALIZING SPARK SESSION")
    print("=" * 70)
    print(f"  CPU Cores: {cpu_cores}")
    print(f"  Configuring for parallel processing...")

    spark = SparkSession.builder \
        .appName("Splink Neo4j Export") \
        .master(f"local[{cpu_cores}]") \
        .config("spark.driver.memory", "4g") \
        .config("spark.executor.memory", "4g") \
        .config("spark.default.parallelism", str(cpu_cores * 2)) \
        .config("spark.sql.shuffle.partitions", str(cpu_cores * 2)) \
        .config("spark.sql.adaptive.enabled", "true") \
        .config("spark.sql.adaptive.coalescePartitions.enabled", "true") \
        .getOrCreate()

    spark.sparkContext.setLogLevel("WARN")
    print(f"  ✓ Spark session created")
    print(f"  ✓ Parallelism: {cpu_cores * 2} partitions")
    print("=" * 70)
    print()
    return spark


def load_records(spark: SparkSession) -> DataFrame:
    """Load record data using the same cache/aggregated rules as splink_commands."""
    cache_path = get_cache_file_path()
    data_path = cache_path if os.path.exists(cache_path) else CUSTOMER_AGGREGATED_PATH

    if not os.path.exists(data_path):
        print(f"✗ ERROR: Record data not found at: {data_path}")
        print(f"  Also checked cache: {cache_path}")
        print("\nPlease ensure parquet data exists at one of these locations.")
        print("You can configure the path via CUSTOMER_AGGREGATED_PATH in .env file")
        sys.exit(1)

    print("=" * 70)
    print("LOADING RECORD DATA")
    print("=" * 70)
    print(f"  Source: {data_path}")

    if data_path == cache_path:
        if CACHE_FORMAT == "parquet":
            df = spark.read.parquet(data_path)
        elif CACHE_FORMAT == "json":
            df = spark.read.json(data_path)
        elif CACHE_FORMAT == "csv":
            df = spark.read.csv(data_path, header=True, inferSchema=True)
        else:
            df = spark.read.parquet(data_path)
    else:
        df = spark.read.parquet(data_path)

    optimal_partitions = multiprocessing.cpu_count() * 2
    df = df.repartition(optimal_partitions)
    print("  ✓ Records loaded")
    print(f"  ✓ Partitions: {optimal_partitions}")
    print("=" * 70)
    print()
    return df


def _resolve_csv_path(csv_path: str) -> str:
    """Resolve a CSV path that may point to a directory or file."""
    if os.path.isdir(csv_path):
        csv_files = glob.glob(os.path.join(csv_path, "*.csv"))
        if not csv_files:
            raise FileNotFoundError(f"No CSV files found in directory: {csv_path}")
        if len(csv_files) > 1:
            print(f"  • Warning: Multiple CSV files found in {csv_path}, using {csv_files[0]}")
        return csv_files[0]
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV file not found: {csv_path}")
    return csv_path


def _resolve_column(df: DataFrame, candidates: List[str], label: str) -> str:
    """Resolve a column name with case-insensitive matching against candidates."""
    columns = df.columns
    lower_map = {col.lower(): col for col in columns}
    for candidate in candidates:
        if candidate in columns:
            return candidate
        candidate_lower = candidate.lower()
        if candidate_lower in lower_map:
            return lower_map[candidate_lower]
    raise ValueError(f"Missing {label} column. Available columns: {columns}")


def export_clusters_to_neo4j(
    clusters: List[Dict],
    matches: List[Dict],
    records_df,
    neo4j_uri: str = None,
    neo4j_user: str = None,
    neo4j_password: str = None
) -> Dict[str, int]:
    """
    Export Splink clusters to Neo4j database.
    
    Args:
        clusters: List of cluster dictionaries with cluster_id and member_indices
        matches: List of match dictionaries with record indices and probabilities
        records_df: Spark DataFrame or pandas DataFrame with record data
        neo4j_uri: Neo4j connection URI (defaults to env variable)
        neo4j_user: Neo4j username (defaults to env variable)
        neo4j_password: Neo4j password (defaults to env variable)
        
    Returns:
        Dictionary with export statistics
    """
    print("=" * 70)
    print("Exporting Splink Clusters to Neo4j")
    print("=" * 70)
    print()
    
    # Use environment variables as defaults
    neo4j_uri = neo4j_uri or NEO4J_URI
    neo4j_user = neo4j_user or NEO4J_USER
    neo4j_password = neo4j_password or NEO4J_PASSWORD
    
    # Convert Spark DataFrame to pandas if needed
    if hasattr(records_df, 'toPandas'):
        print("Converting Spark DataFrame to pandas...")
        records_pd = records_df.toPandas()
        print("✓ Conversion complete")
        print()
    else:
        records_pd = records_df
    
    # Create index mapping for quick lookups
    print("Creating record index mapping...")
    if 'unique_id' in records_pd.columns:
        record_map = records_pd.set_index('unique_id').to_dict('index')
    else:
        record_map = {i: row for i, row in records_pd.iterrows()}
    print(f"✓ Indexed {len(record_map):,} records")
    print()
    
    # Connect to Neo4j
    print(f"Connecting to Neo4j at {neo4j_uri}...")
    try:
        driver = GraphDatabase.driver(neo4j_uri, auth=(neo4j_user, neo4j_password))
        # Test connection
        with driver.session() as session:
            session.run("RETURN 1")
        print("✓ Connected to Neo4j")
        print()
    except Exception as e:
        print(f"ERROR: Could not connect to Neo4j: {e}")
        print("\nMake sure Neo4j is running and credentials are correct.")
        print("Check your .env file or environment variables:")
        print(f"  NEO4J_USER={neo4j_user}")
        print("Skipping Neo4j export gracefully...")
        return {
            'clusters_created': 0,
            'entities_created': 0,
            'member_relationships': 0,
            'duplicate_relationships': 0
        }
    
    stats = {
        'clusters_created': 0,
        'entities_created': 0,
        'member_relationships': 0,
        'duplicate_relationships': 0
    }
    
    try:
        with driver.session() as session:
            # Clear existing entity resolution graph
            print("Clearing existing EntityCluster and Entity nodes...")
            session.run("MATCH (n:EntityCluster) DETACH DELETE n")
            session.run("MATCH (n:Entity) DETACH DELETE n")
            print("✓ Cleared existing data")
            print()
            
            # Create clusters and entities
            print(f"Creating {len(clusters):,} entity clusters...")
            
            for cluster_idx, cluster in enumerate(clusters):
                cluster_id = cluster['cluster_id']
                member_indices = cluster['member_indices']
                
                # Create cluster node
                session.run(
                    """
                    CREATE (c:EntityCluster {
                        cluster_id: $cluster_id,
                        size: $size,
                        created_at: datetime()
                    })
                    """,
                    cluster_id=str(cluster_id),
                    size=len(member_indices)
                )
                stats['clusters_created'] += 1
                
                # Create entity nodes and relationships
                for idx in member_indices:
                    record = record_map.get(idx, {})
                    
                    # Create entity node with record properties
                    entity_props = {
                        'entity_id': str(idx),
                        'name': record.get('NAME', ''),
                        'email': record.get('EMAIL', ''),
                        'mobile': record.get('MOBILE', ''),
                        'telephone': record.get('TELEPHONE', ''),
                        'address': record.get('FULL_ADDRESS', ''),
                        'birth_date': record.get('BIRTH_DATE', ''),
                        'document_number': record.get('DOCUMENT_NUMBER', ''),
                        'customer_code': record.get('CUSTOMER_CODE', ''),
                        'branch_code': record.get('BRANCH_CODE', '')
                    }
                    
                    # Remove None values
                    entity_props = {k: v for k, v in entity_props.items() if v is not None}
                    
                    session.run(
                        """
                        CREATE (e:Entity $props)
                        """,
                        props=entity_props
                    )
                    stats['entities_created'] += 1
                    
                    # Create MEMBER_OF relationship
                    session.run(
                        """
                        MATCH (e:Entity {entity_id: $entity_id})
                        MATCH (c:EntityCluster {cluster_id: $cluster_id})
                        CREATE (e)-[:MEMBER_OF]->(c)
                        """,
                        entity_id=str(idx),
                        cluster_id=str(cluster_id)
                    )
                    stats['member_relationships'] += 1
                
                # Progress indicator using cluster_idx
                if (cluster_idx + 1) % 100 == 0:
                    print(f"  Processed {cluster_idx + 1:,} clusters...")
            
            print(f"✓ Created {stats['clusters_created']:,} clusters")
            print(f"✓ Created {stats['entities_created']:,} entities")
            print(f"✓ Created {stats['member_relationships']:,} MEMBER_OF relationships")
            print()
            
            # Create DUPLICATE_OF relationships between matching entities
            print(f"Creating {len(matches):,} DUPLICATE_OF relationships...")
            
            for i, match in enumerate(matches):
                id1 = match.get('id1') or match.get('record1_idx')
                id2 = match.get('id2') or match.get('record2_idx')
                probability = match.get('probability', 0.0)
                
                session.run(
                    """
                    MATCH (e1:Entity {entity_id: $id1})
                    MATCH (e2:Entity {entity_id: $id2})
                    CREATE (e1)-[:DUPLICATE_OF {
                        probability: $probability,
                        created_at: datetime()
                    }]->(e2)
                    """,
                    id1=str(id1),
                    id2=str(id2),
                    probability=float(probability)
                )
                stats['duplicate_relationships'] += 1
                
                # Progress indicator
                if (i + 1) % 1000 == 0:
                    print(f"  Processed {i + 1:,} relationships...")
            
            print(f"✓ Created {stats['duplicate_relationships']:,} DUPLICATE_OF relationships")
            print()
            
            # Create indexes for better query performance
            print("Creating indexes for better performance...")
            session.run("CREATE INDEX entity_id_index IF NOT EXISTS FOR (e:Entity) ON (e.entity_id)")
            session.run("CREATE INDEX cluster_id_index IF NOT EXISTS FOR (c:EntityCluster) ON (c.cluster_id)")
            print("✓ Indexes created")
            print()
    
    finally:
        driver.close()
    
    print("=" * 70)
    print("Export Summary")
    print("=" * 70)
    print(f"Clusters created: {_format_count(stats['clusters_created'])}")
    print(f"Entities created: {_format_count(stats['entities_created'])}")
    print(f"MEMBER_OF relationships: {_format_count(stats['member_relationships'])}")
    print(f"DUPLICATE_OF relationships: {_format_count(stats['duplicate_relationships'])}")
    print()
    
    return stats


def export_clusters_csv_to_neo4j(
    spark: SparkSession,
    clusters_csv: str,
    records_df,
    neo4j_uri: str = None,
    neo4j_user: str = None,
    neo4j_password: str = None,
    batch_size: int = _NEO4J_DEFAULT_BATCH_SIZE,
    materialize_dir: Optional[str] = None
) -> Dict[str, int]:
    """Export cluster CSV output from splink_commands to Neo4j using Spark."""
    batch_size = _normalize_neo4j_batch_size(
        batch_size or _NEO4J_DEFAULT_BATCH_SIZE, "neo4j batch size"
    )
    print("=" * 70)
    print("Exporting Splink Clusters to Neo4j (CSV + Spark)")
    print("=" * 70)
    print()

    neo4j_uri = neo4j_uri or NEO4J_URI
    neo4j_user = neo4j_user or NEO4J_USER
    neo4j_password = neo4j_password or NEO4J_PASSWORD

    clusters_path = _resolve_csv_path(clusters_csv)
    clusters_df = spark.read.csv(clusters_path, header=True, inferSchema=True)
    original_columns = clusters_df.columns

    cluster_id_col = _resolve_column(clusters_df, ["cluster_id"], "cluster_id")
    entity_id_col = _resolve_column(clusters_df, ["CUSTOMER_CODE", "unique_id"], "entity identifier")

    clusters_df = clusters_df.withColumn(CLUSTER_ID_FIELD, F.col(cluster_id_col).cast("string"))
    clusters_df = clusters_df.withColumn(ENTITY_ID_FIELD, F.col(entity_id_col).cast("string"))
    clusters_df = clusters_df.filter(
        F.col(CLUSTER_ID_FIELD).isNotNull() & F.col(ENTITY_ID_FIELD).isNotNull()
    )

    extra_columns = [col for col in original_columns if col not in {cluster_id_col, entity_id_col}]
    has_extra_columns = bool(extra_columns)
    entity_cluster_mapping_df = clusters_df.select(CLUSTER_ID_FIELD, ENTITY_ID_FIELD)
    # If the clustering CSV already includes properties, keep them; otherwise start minimal.
    entity_df = clusters_df if has_extra_columns else entity_cluster_mapping_df
    record_columns = None
    if records_df is not None and not has_extra_columns:
        record_id_col = _resolve_column(records_df, [entity_id_col, "CUSTOMER_CODE", "unique_id"], "record identifier")
        records_df = records_df.withColumn(ENTITY_ID_FIELD, F.col(record_id_col).cast("string"))
        record_columns = _exportable_entity_columns(records_df.columns)
        if record_columns:
            records_df = records_df.select(ENTITY_ID_FIELD, *record_columns)
            entity_df = entity_cluster_mapping_df.join(records_df, ENTITY_ID_FIELD, "left")
    selected_columns = (
        record_columns
        if record_columns is not None
        else _exportable_entity_columns(entity_df.columns)
    )
    entity_df = entity_df.select(CLUSTER_ID_FIELD, ENTITY_ID_FIELD, *selected_columns)
    if selected_columns:
        print(f"  - Exporting entity properties: {', '.join(selected_columns)}")
    else:
        print(
            "  - Exporting entity_id only. Set NEO4J_ENTITY_COLUMNS (comma-separated list) "
            "to include record properties for export."
        )

    cluster_sizes_df = clusters_df.groupBy(CLUSTER_ID_FIELD).count().withColumnRenamed("count", "size")
    # Aggregate entity IDs per cluster to reduce MEMBER_OF relationship insert overhead.
    member_of_df = entity_cluster_mapping_df.groupBy(CLUSTER_ID_FIELD).agg(
        F.collect_list(ENTITY_ID_FIELD).alias("entity_ids")
    )
    entity_nodes_df = entity_df.drop(CLUSTER_ID_FIELD)

    materialize_dir = materialize_dir or NEO4J_MATERIALIZE_DIR
    try:
        os.makedirs(materialize_dir, exist_ok=True)
    except OSError as exc:
        print(f"ERROR: Could not create materialization dir '{materialize_dir}': {exc}")
        print("  - Ensure the path is a directory and you have write permissions.")
        sys.exit(1)
    clusters_path = os.path.join(materialize_dir, "clusters")
    entities_path = os.path.join(materialize_dir, "entities")
    member_of_path = os.path.join(materialize_dir, "member_of")

    print("=" * 70)
    print("MATERIALIZING NODE/EDGE DATA")
    print("=" * 70)
    print(f"  Materialization dir: {materialize_dir}")
    print("  Writing clusters, entities, and member_of edges...")
    try:
        cluster_sizes_df.write.mode("overwrite").parquet(clusters_path)
        entity_nodes_df.write.mode("overwrite").parquet(entities_path)
        member_of_df.write.mode("overwrite").parquet(member_of_path)
    except (OSError, Py4JJavaError) as exc:
        print(f"ERROR: Materialization failed ({type(exc).__name__}): {exc}")
        print("  - Check disk space, permissions, and schema consistency.")
        print("  - Clear the materialization directory before retrying.")
        sys.exit(1)
    print("  ✓ Materialization complete")
    print()

    # Spark caches lazily; data is populated on the first action (e.g., count or foreachPartition).
    cluster_sizes_df = spark.read.parquet(clusters_path).cache()
    entity_nodes_df = spark.read.parquet(entities_path).cache()
    member_of_df = spark.read.parquet(member_of_path).cache()

    print(f"Connecting to Neo4j at {neo4j_uri}...")
    try:
        driver = GraphDatabase.driver(neo4j_uri, auth=(neo4j_user, neo4j_password))
        with driver.session() as session:
            session.run("RETURN 1")
        print("✓ Connected to Neo4j")
        print()
    except Exception as e:
        print(f"ERROR: Could not connect to Neo4j: {e}")
        print("\nMake sure Neo4j is running and credentials are correct.")
        print("Check your .env file or environment variables:")
        print(f"  NEO4J_USER={neo4j_user}")
        print("Skipping Neo4j export gracefully...")
        return {
            'clusters_created': 0,
            'entities_created': 0,
            'member_relationships': 0,
            'duplicate_relationships': 0
        }

    # while keeping a minimum batch size to avoid transaction memory spikes.
    delete_batch_multiplier = 5
    delete_batch_min = 5000
    delete_log_multiplier = 5
    delete_log_min = 25000
    delete_batch_size = max(batch_size * delete_batch_multiplier, delete_batch_min)
    delete_log_every = max(delete_batch_size * delete_log_multiplier, delete_log_min)
    delete_queries = {
        "Entity": "MATCH (n:Entity) WITH n LIMIT $limit DETACH DELETE n RETURN count(*) AS deleted",
        "EntityCluster": (
            "MATCH (n:EntityCluster) WITH n LIMIT $limit DETACH DELETE n "
            "RETURN count(*) AS deleted"
        ),
    }

    def _delete_nodes_by_label(session, label: str) -> None:
        allowed_labels = {"Entity", "EntityCluster"}
        if label not in allowed_labels:
            raise ValueError(f"Unsupported label for deletion: {label}")
        delete_query = delete_queries[label]
        total_deleted = 0
        last_logged = 0
        while True:
            result = session.run(
                delete_query,
                limit=delete_batch_size
            )
            deleted = result.single()["deleted"]
            if deleted == 0:
                break
            total_deleted += deleted
            if total_deleted - last_logged >= delete_log_every:
                print(f"  - Deleted {total_deleted:,} {label} nodes...")
                sys.stdout.flush()
                last_logged = total_deleted
        if total_deleted:
            print(f"  - Deleted {total_deleted:,} {label} nodes")

    try:
        with driver.session() as session:
            print("Clearing existing Entity and EntityCluster nodes (batched)...")
            _delete_nodes_by_label(session, "Entity")
            _delete_nodes_by_label(session, "EntityCluster")
            print("✓ Cleared existing data")
            print()
    finally:
        driver.close()

    # Convert Spark DataFrames to pandas to avoid Python worker serialization issues
    # This is more reliable than foreachPartition with UDFs
    print("=" * 70)
    print("CONVERTING TO PANDAS FOR NEO4J WRITE")
    print("=" * 70)
    print("Converting cluster data to pandas...")
    clusters_pd = cluster_sizes_df.toPandas()
    print(f"  ✓ {len(clusters_pd):,} clusters")
    
    print("Converting entity data to pandas...")
    entities_pd = entity_nodes_df.toPandas()
    print(f"  ✓ {len(entities_pd):,} entities")
    
    print("Converting relationship data to pandas...")
    member_of_pd = member_of_df.toPandas()
    print(f"  ✓ {len(member_of_pd):,} cluster-entity mappings")
    print("=" * 70)
    print()
    
    # Update stats with actual counts
    stats = {
        'clusters_created': len(clusters_pd),
        'entities_created': len(entities_pd),
        'member_relationships': 0,  # Will be calculated during insert
        'duplicate_relationships': 0
    }
    
    # Cypher queries for batch inserts
    create_cluster_query = """
        UNWIND $rows AS row
        CREATE (c:EntityCluster {
            cluster_id: row.cluster_id,
            size: row.size,
            created_at: datetime()
        })
    """
    create_entity_query = """
        UNWIND $rows AS row
        CREATE (e:Entity)
        SET e = row.props
    """
    create_member_query = """
        UNWIND $rows AS row
        MATCH (c:EntityCluster {cluster_id: row.cluster_id})
        UNWIND row.entity_ids AS entity_id
        MATCH (e:Entity {entity_id: entity_id})
        CREATE (e)-[:MEMBER_OF]->(c)
    """

    # Connect to Neo4j
    driver = GraphDatabase.driver(neo4j_uri, auth=(neo4j_user, neo4j_password))
    
    try:
        # 1. Create clusters
        print(f"Creating {len(clusters_pd):,} clusters in Neo4j...")
        with driver.session() as session:
            batch = []
            for idx, row in clusters_pd.iterrows():
                cluster_id = row["cluster_id"]
                size = row["size"]
                if cluster_id is None:
                    continue
                batch.append({"cluster_id": str(cluster_id), "size": int(size)})
                
                if len(batch) >= batch_size:
                    session.run(create_cluster_query, rows=batch)
                    batch = []
                    if (idx + 1) % 5000 == 0:
                        print(f"  • Created {idx + 1:,} clusters...")
            
            if batch:
                session.run(create_cluster_query, rows=batch)
        print("✓ Created clusters")
        print()
        
        # 2. Create entities
        print(f"Creating {len(entities_pd):,} entities in Neo4j...")
        with driver.session() as session:
            batch = []
            for idx, row in entities_pd.iterrows():
                row_dict = row.to_dict()
                entity_id = row_dict.pop(ENTITY_ID_FIELD, None)
                if entity_id is None:
                    continue
                props = {k: v for k, v in row_dict.items() if v is not None and str(v) != 'nan'}
                props["entity_id"] = str(entity_id)
                batch.append({"props": props})
                
                if len(batch) >= batch_size:
                    session.run(create_entity_query, rows=batch)
                    batch = []
                    if (idx + 1) % 5000 == 0:
                        print(f"  • Created {idx + 1:,} entities...")
            
            if batch:
                session.run(create_entity_query, rows=batch)
        print("✓ Created entities")
        print()
        
        # 3. Create indexes before relationships for better performance
        print("Creating indexes for better performance...")
        with driver.session() as session:
            session.run("CREATE INDEX entity_id_index IF NOT EXISTS FOR (e:Entity) ON (e.entity_id)")
            session.run("CREATE INDEX cluster_id_index IF NOT EXISTS FOR (c:EntityCluster) ON (c.cluster_id)")
        print("✓ Indexes created")
        print()
        
        # 4. Create MEMBER_OF relationships
        print(f"Creating MEMBER_OF relationships...")
        with driver.session() as session:
            rows_batch = []
            batch_relationships = 0
            total_relationships = 0
            
            for idx, row in member_of_pd.iterrows():
                cluster_id = row[CLUSTER_ID_FIELD]
                entity_ids = row["entity_ids"]
                
                if cluster_id is None or not entity_ids:
                    continue
                
                entity_ids = [str(eid) for eid in entity_ids]
                
                # Split large clusters into chunks
                for start in range(0, len(entity_ids), batch_size):
                    entity_chunk = entity_ids[start:start + batch_size]
                    rows_batch.append({"cluster_id": str(cluster_id), "entity_ids": entity_chunk})
                    batch_relationships += len(entity_chunk)
                    
                    # Execute when we have enough rows or relationships
                    if len(rows_batch) >= 100 or batch_relationships >= _MEMBER_BATCH_TARGET:
                        session.run(create_member_query, rows=rows_batch)
                        total_relationships += batch_relationships
                        if total_relationships % 10000 == 0:
                            print(f"  • Created {total_relationships:,} MEMBER_OF relationships...")
                        rows_batch = []
                        batch_relationships = 0
            
            if rows_batch:
                session.run(create_member_query, rows=rows_batch)
                total_relationships += batch_relationships
        
        print(f"✓ Created {total_relationships:,} MEMBER_OF relationships")
        print("  • Skipping DUPLICATE_OF relationships (clusters CSV only)")
        print()
        
        stats['member_relationships'] = total_relationships
        
    finally:
        driver.close()
        
        # Release cached materialized dataframes
        for dataframe in (cluster_sizes_df, entity_nodes_df, member_of_df):
            try:
                dataframe.unpersist()
            except Exception as exc:
                print(f"  - Warning: Could not unpersist dataframe: {exc}")

    print("=" * 70)
    print("Export Summary")
    print("=" * 70)
    print(f"Clusters created: {_format_count(stats['clusters_created'])}")
    print(f"Entities created: {_format_count(stats['entities_created'])}")
    print(f"MEMBER_OF relationships: {_format_count(stats['member_relationships'])}")
    print(f"DUPLICATE_OF relationships: {_format_count(stats['duplicate_relationships'])}")
    print()

    return stats


def main():
    """Main entry point for exporting Splink clusters to Neo4j."""
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Export Splink clusters to Neo4j database"
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=0.8,
        help="Match probability threshold for clustering (0.0-1.0, default: 0.8)"
    )
    parser.add_argument(
        "--clusters-csv",
        type=str,
        default=None,
        help="Cluster CSV output from splink_commands (e.g., my_clustering_results.csv)"
    )
    parser.add_argument(
        "--neo4j-uri",
        type=str,
        default=None,
        help="Neo4j URI (default: from .env file)"
    )
    parser.add_argument(
        "--neo4j-user",
        type=str,
        default=None,
        help="Neo4j username (default: from .env file)"
    )
    parser.add_argument(
        "--neo4j-password",
        type=str,
        default=None,
        help="Neo4j password (default: from .env file)"
    )
    parser.add_argument(
        "--neo4j-batch-size",
        type=int,
        default=None,
        help=f"Batch size for Neo4j inserts (default: {_NEO4J_DEFAULT_BATCH_SIZE})"
    )
    parser.add_argument(
        "--materialize-dir",
        type=str,
        default=None,
        help=f"Directory to materialize nodes/edges before Neo4j load (default: {NEO4J_MATERIALIZE_DIR})"
    )
    parser.add_argument(
        "--skip-clustering",
        action="store_true",
        help="Skip clustering step (use if already clustered)"
    )
    
    args = parser.parse_args()
    
    try:
        spark = create_spark_session()

        if args.clusters_csv:
            batch_size = _resolve_neo4j_batch_size(args.neo4j_batch_size)
            records_df = load_records(spark)
            export_clusters_csv_to_neo4j(
                spark=spark,
                clusters_csv=args.clusters_csv,
                records_df=records_df,
                neo4j_uri=args.neo4j_uri,
                neo4j_user=args.neo4j_user,
                neo4j_password=args.neo4j_password,
                batch_size=batch_size,
                materialize_dir=args.materialize_dir
            )
        else:
            try:
                from engine.spark_er.splink_clustering import run_splink_clustering, load_data_from_cache
            except ImportError:
                print("=" * 70)
                print("ERROR: Could not import splink_clustering module")
                print("=" * 70)
                print("\nMake sure splink_clustering.py exists in the er/ directory.")
                print("=" * 70)
                sys.exit(1)

            records_df = load_data_from_cache(spark)

            if not args.skip_clustering:
                clusters, matches = run_splink_clustering(
                    spark=spark,
                    match_threshold=args.threshold
                )
            else:
                print("Skipping clustering step...")
                print("WARNING: This option requires clusters/matches to be available")
                print("Use --skip-clustering only if you have custom clustering logic")
                sys.exit(1)

            export_clusters_to_neo4j(
                clusters=clusters,
                matches=matches,
                records_df=records_df,
                neo4j_uri=args.neo4j_uri,
                neo4j_user=args.neo4j_user,
                neo4j_password=args.neo4j_password
            )
        
        print("✓ Export complete!")
        print()
        print("You can now query the clusters in Neo4j:")
        print("  MATCH (c:EntityCluster) RETURN c LIMIT 10")
        print("  MATCH (e:Entity)-[:MEMBER_OF]->(c:EntityCluster) RETURN e, c LIMIT 10")
        
        return 0
        
    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    finally:
        if 'spark' in locals():
            spark.stop()


if __name__ == "__main__":
    sys.exit(main())
