-- ============================================
-- CUIN v2 Control Plane - Database Schema
-- ============================================
-- PostgreSQL 15+ required
-- Run with: psql -U cuin -d cuin_db -f schema.sql
-- ============================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================
-- RUNS TABLE
-- Tracks each ER pipeline execution
-- ============================================
CREATE TABLE IF NOT EXISTS runs (
    run_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    mode VARCHAR(10) NOT NULL CHECK (mode IN ('FULL', 'DELTA')),
    policy_version INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' 
        CHECK (status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    description TEXT,
    
    -- Counters
    records_in INTEGER DEFAULT 0,
    records_normalized INTEGER DEFAULT 0,
    blocks_created INTEGER DEFAULT 0,
    candidates_generated INTEGER DEFAULT 0,
    pairs_scored INTEGER DEFAULT 0,
    auto_links INTEGER DEFAULT 0,
    review_items INTEGER DEFAULT 0,
    rejected INTEGER DEFAULT 0,
    
    -- Timing
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE,
    
    -- Error handling
    error_message TEXT,
    error_stack TEXT,
    
    -- Metadata
    created_by VARCHAR(255),
    
    CONSTRAINT valid_dates CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE INDEX idx_runs_status ON runs(status);
CREATE INDEX idx_runs_started_at ON runs(started_at DESC);

-- ============================================
-- POLICY VERSIONS TABLE
-- Versioned policy configurations with maker-checker
-- ============================================
CREATE TABLE IF NOT EXISTS policy_versions (
    policy_version SERIAL PRIMARY KEY,
    policy_yaml TEXT NOT NULL,
    policy_hash VARCHAR(64) NOT NULL,  -- SHA-256 for change detection
    
    -- Maker-checker workflow
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    approved_by VARCHAR(255),
    approved_at TIMESTAMP WITH TIME ZONE,
    
    -- Status
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Only one active policy at a time
    CONSTRAINT one_active_policy EXCLUDE (is_active WITH =) WHERE (is_active = TRUE)
);

-- ============================================
-- CUSTOMERS NORMALIZED TABLE
-- Normalized staging data (read from traditional team)
-- ============================================
CREATE TABLE IF NOT EXISTS customers_norm (
    customer_key UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_customer_id VARCHAR(50) NOT NULL,
    
    -- Normalized fields
    name_norm VARCHAR(500),
    phone_norm VARCHAR(20),
    email_norm VARCHAR(255),
    dob_norm DATE,
    address_norm TEXT,
    city_norm VARCHAR(100),
    natid_norm VARCHAR(50),
    
    -- Change detection
    record_hash VARCHAR(64) NOT NULL,  -- Hash of canonicalized fields
    
    -- Metadata
    source_system VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    CONSTRAINT unique_source_id UNIQUE (source_customer_id, source_system)
);

CREATE INDEX idx_customers_record_hash ON customers_norm(record_hash);
CREATE INDEX idx_customers_updated_at ON customers_norm(updated_at);
CREATE INDEX idx_customers_phone ON customers_norm(phone_norm);
CREATE INDEX idx_customers_email ON customers_norm(email_norm);

-- ============================================
-- CANDIDATE PAIRS TABLE
-- Pairs generated by blocking
-- ============================================
CREATE TABLE IF NOT EXISTS candidate_pairs (
    pair_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id UUID NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    a_key UUID NOT NULL REFERENCES customers_norm(customer_key),
    b_key UUID NOT NULL REFERENCES customers_norm(customer_key),
    
    -- Blocking provenance
    blocking_reasons TEXT[] NOT NULL,  -- e.g., ['phone_last10', 'soundex_full']
    block_key_sample TEXT,  -- Sample key for debugging
    
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    
    -- Ensure ordered pairs (a < b) to avoid duplicates
    CONSTRAINT ordered_pair CHECK (a_key < b_key),
    CONSTRAINT unique_pair_per_run UNIQUE (run_id, a_key, b_key)
);

CREATE INDEX idx_candidates_run ON candidate_pairs(run_id);
CREATE INDEX idx_candidates_a_key ON candidate_pairs(a_key);
CREATE INDEX idx_candidates_b_key ON candidate_pairs(b_key);

-- ============================================
-- MATCH SCORES TABLE
-- Splink scoring results
-- ============================================
CREATE TABLE IF NOT EXISTS match_scores (
    pair_id UUID PRIMARY KEY REFERENCES candidate_pairs(pair_id) ON DELETE CASCADE,
    run_id UUID NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    
    score DECIMAL(5,4) NOT NULL CHECK (score >= 0 AND score <= 1),
    
    -- Explainability
    evidence_json JSONB NOT NULL,  -- Feature contributions
    
    scored_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_scores_run ON match_scores(run_id);
CREATE INDEX idx_scores_score ON match_scores(score);

-- ============================================
-- MATCH DECISIONS TABLE
-- Final decisions (AUTO_LINK, REVIEW, REJECT)
-- ============================================
CREATE TABLE IF NOT EXISTS match_decisions (
    pair_id UUID PRIMARY KEY REFERENCES candidate_pairs(pair_id) ON DELETE CASCADE,
    run_id UUID NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    
    decision VARCHAR(20) NOT NULL 
        CHECK (decision IN ('AUTO_LINK', 'REVIEW', 'REJECT')),
    
    -- Decision context
    threshold_used DECIMAL(5,4) NOT NULL,
    signals_hit TEXT[],
    hard_conflict_flags TEXT[],
    
    -- Optional referee explanation reference
    llm_explanation_id UUID,
    
    decided_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_decisions_run ON match_decisions(run_id);
CREATE INDEX idx_decisions_decision ON match_decisions(decision);

-- ============================================
-- REVIEW QUEUE TABLE
-- Human review workflow
-- ============================================
CREATE TABLE IF NOT EXISTS review_queue (
    pair_id UUID PRIMARY KEY REFERENCES candidate_pairs(pair_id) ON DELETE CASCADE,
    run_id UUID NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    
    state VARCHAR(20) NOT NULL DEFAULT 'OPEN'
        CHECK (state IN ('OPEN', 'APPROVED', 'REJECTED')),
    
    -- Review decision
    reason_code VARCHAR(50),
    review_note TEXT,
    
    -- Reviewer info
    reviewed_by VARCHAR(255),
    reviewed_at TIMESTAMP WITH TIME ZONE,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_review_state ON review_queue(state);
CREATE INDEX idx_review_run ON review_queue(run_id);

-- ============================================
-- CLUSTERS TABLE
-- Union-find clustering results
-- ============================================
CREATE TABLE IF NOT EXISTS clusters (
    id SERIAL PRIMARY KEY,
    cluster_id UUID NOT NULL,
    customer_key UUID NOT NULL REFERENCES customers_norm(customer_key),
    
    -- Versioning
    active_version INTEGER NOT NULL,
    valid_from TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    valid_to TIMESTAMP WITH TIME ZONE,
    
    CONSTRAINT unique_customer_cluster_version UNIQUE (cluster_id, customer_key, active_version)
);

CREATE INDEX idx_clusters_cluster_id ON clusters(cluster_id);
CREATE INDEX idx_clusters_customer_key ON clusters(customer_key);
CREATE INDEX idx_clusters_valid ON clusters(valid_from, valid_to);

-- ============================================
-- GOLDEN RECORDS TABLE
-- Merged golden identity records
-- ============================================
CREATE TABLE IF NOT EXISTS golden_records (
    id SERIAL PRIMARY KEY,
    cluster_id UUID NOT NULL,
    version INTEGER NOT NULL,
    
    -- Golden payload (merged fields)
    golden_payload_json JSONB NOT NULL,
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by VARCHAR(255),
    
    CONSTRAINT unique_golden_version UNIQUE (cluster_id, version)
);

CREATE INDEX idx_golden_cluster ON golden_records(cluster_id);

-- ============================================
-- AUDIT EVENTS TABLE
-- Append-only tamper-evident audit log
-- ============================================
CREATE TABLE IF NOT EXISTS audit_events (
    audit_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    run_id UUID REFERENCES runs(run_id),
    
    event_type VARCHAR(50) NOT NULL,
    payload_json JSONB NOT NULL,
    
    -- Actor (user or system)
    actor VARCHAR(255),
    
    -- Hash chain for tamper evidence
    prev_hash VARCHAR(64) NOT NULL,
    this_hash VARCHAR(64) NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- Append-only: no updates or deletes allowed via application
-- Use database-level audit or triggers for enforcement

CREATE INDEX idx_audit_run ON audit_events(run_id);
CREATE INDEX idx_audit_type ON audit_events(event_type);
CREATE INDEX idx_audit_created ON audit_events(created_at);

-- ============================================
-- REFEREE EXPLANATIONS TABLE
-- LLM-generated explanations for gray-zone pairs
-- ============================================
CREATE TABLE IF NOT EXISTS referee_explanations (
    llm_explanation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    pair_id UUID NOT NULL REFERENCES candidate_pairs(pair_id) ON DELETE CASCADE,
    run_id UUID NOT NULL REFERENCES runs(run_id) ON DELETE CASCADE,
    
    -- Explanation content
    explanation_text TEXT NOT NULL,
    evidence_summary_json JSONB,
    
    -- Model info
    model_name VARCHAR(100),
    model_version VARCHAR(50),
    
    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_referee_pair ON referee_explanations(pair_id);
CREATE INDEX idx_referee_run ON referee_explanations(run_id);

-- ============================================
-- INITIAL DATA
-- ============================================

-- Insert genesis audit event (for hash chain)
INSERT INTO audit_events (
    audit_id,
    event_type,
    payload_json,
    actor,
    prev_hash,
    this_hash,
    created_at
) VALUES (
    '00000000-0000-0000-0000-000000000000',
    'SYSTEM_GENESIS',
    '{"message": "CUIN v2 audit chain initialized"}'::jsonb,
    'SYSTEM',
    '0000000000000000000000000000000000000000000000000000000000000000',
    encode(sha256('GENESIS'::bytea), 'hex'),
    NOW()
) ON CONFLICT DO NOTHING;

-- ============================================
-- HELPER FUNCTIONS
-- ============================================

-- Function to compute next audit hash
CREATE OR REPLACE FUNCTION compute_audit_hash(
    p_prev_hash VARCHAR(64),
    p_event_type VARCHAR(50),
    p_payload JSONB,
    p_created_at TIMESTAMP WITH TIME ZONE
) RETURNS VARCHAR(64) AS $$
BEGIN
    RETURN encode(
        sha256(
            (p_prev_hash || p_event_type || p_payload::text || p_created_at::text)::bytea
        ),
        'hex'
    );
END;
$$ LANGUAGE plpgsql IMMUTABLE;

-- ============================================
-- COMMENTS
-- ============================================

COMMENT ON TABLE runs IS 'ER pipeline execution tracking';
COMMENT ON TABLE policy_versions IS 'Versioned policy configurations with maker-checker approval';
COMMENT ON TABLE customers_norm IS 'Normalized customer records from staging';
COMMENT ON TABLE candidate_pairs IS 'Candidate pairs generated by multi-pass blocking';
COMMENT ON TABLE match_scores IS 'Splink probabilistic match scores with evidence';
COMMENT ON TABLE match_decisions IS 'Final decisions: AUTO_LINK, REVIEW, or REJECT';
COMMENT ON TABLE review_queue IS 'Human review queue with maker-checker workflow';
COMMENT ON TABLE clusters IS 'Union-find clustering with versioning';
COMMENT ON TABLE golden_records IS 'Merged golden identity records';
COMMENT ON TABLE audit_events IS 'Append-only tamper-evident audit log';
COMMENT ON TABLE referee_explanations IS 'AI-generated explanations for review assistance';
